export enum ActionType {

  LOGIN = "LOGIN",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",

  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

  REGISTER_USER = "REGISTER_USER",
  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILED = "REGISTER_USER_FAILED",

  GET_USER_LIST = "GET_USER_LIST",
  GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL"
}